In [2]:
import numpy as np
mylist1=[1,2,3,4]
myarray=np.array(mylist1)
myarray

array([1, 2, 3, 4])

In [3]:
mylist2=[11,22,33,44]

In [5]:
mylist=[mylist1,mylist2] #here we have not concatenated but 2 sublist are added

In [8]:
myarray2=np.array(mylist)
myarray2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [9]:
myarray2.shape

(2, 4)

In [10]:
myarray.shape

(4,)

In [11]:
myarray2.dtype

dtype('int32')

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.ones(3)

array([1., 1., 1.])

In [18]:
zer_array=np.zeros(5)
zer_array.dtype

dtype('float64')

In [20]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
np.empty(5)       #this creates array havinf negligible values

array([0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 7.15407055e-321,
       1.29441743e-312])

In [22]:
np.eye(5)         #eye is for identity matrix of size 5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [25]:
np.arange(5,49,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47])

In [26]:
np.arange(0,5,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [ ]:
np.arange(2,1)